### ISSUE TITLE
Error: `Not an editor command`

### ISSUE THREAD

**Issue by refaelsh** [shuntaka9576/preview-asciidoc.nvim#6]
I get the following error when running `:AsciiDocPreview`:
```
E492: Not an editor command :AsciiDocPreview
```

I installed the plugin using `packer` like this:
```
use 'shuntaka9576/preview-asciidoc.nvim '
```

Please help :-)

**Comment by shuntaka9576** [comment]
You may need to adjust the run settings for this. [ref](https://github.com/wbthomason/packer.nvim/blob/master/README.md?plain=1#L123)


```lua
use { 'shuntaka9576/preview-asciidoc.nvim', run = 'yarn install' }
```

Sorry, however, this plugin has become legacy and maintenance has not kept up with it.
There is a high possibility that it will not work.

If there is enough demand for it, we will re-release it as a separate plugin.

**Comment by refaelsh** [comment]
> use { 'shuntaka9576/preview-asciidoc.nvim', run = 'yarn install' }

This did not help.

> this plugin has become legacy

Oh! Ok. Then you suggest I should not use this plugin? If yes, got suggestions for other plugin with this kind of functionality?

> If there is enough demand for it, we will re-release it as a separate plugin.

Re-release? I dont understand.
